version: "3.4"

services:
  ib-api-service:
    container_name: ib-api-service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-live}
      NODE_ENV: production
    ports:
      - 3002:3002
