version: "3.4"

services:
  ib-api-service:
    container_name: ib-api-service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TWSUSERID: ${TWS_USERID}
      TWSPASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-live}
      NODE_ENV: production
    ports:
      - 3002:3000
