name: "Test and Publish"

on:
  push:
    branches:
      - "master"
env:
  IMAGE_NAME: ib-api-service

jobs:
  publish-package:
    name: "Publish Package"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          node-version: "14.x"
          registry-url: 'https://npm.pkg.github.com'
          scope: "@waytrade"
          always-auth: true

      - name: "Install OpenAPI Tools"
        run: npm install --global @openapitools/openapi-generator-cli

      - name: "Install Dependencies"
        run: yarn install

      - name: "Build Code"
        run: yarn build

      - name: "Run Tests"
        run: yarn test

      - name: "Validate API"
        run: yarn validate-openapi

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Publish to github"
        run: | 
          npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup npmjs registry"
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - name: "Publish to npmjs"
        run: |
          npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
